"""init schema

Revision ID: 8fbc8e5ce2ac
Revises: 
Create Date: 2026-06-28 09:52:04.485176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8fbc8e5ce2ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('CATTLE', name='animaltype'), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('breed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'DECEASED', name='animalstatus'), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_breed'), 'animal', ['breed'], unique=False)
    op.create_index(op.f('ix_animal_deleted_at'), 'animal', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_animal_status'), 'animal', ['status'], unique=False)
    op.create_index(op.f('ix_animal_type'), 'animal', ['type'], unique=False)
    op.create_index('uq_animal_type_tag_live', 'animal', ['type', 'tag'], unique=True, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_animal_type_tag_live', table_name='animal', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_animal_type'), table_name='animal')
    op.drop_index(op.f('ix_animal_status'), table_name='animal')
    op.drop_index(op.f('ix_animal_deleted_at'), table_name='animal')
    op.drop_index(op.f('ix_animal_breed'), table_name='animal')
    op.drop_table('animal')
    # ### end Alembic commands ###
    # Native PG enum types are not dropped with the table; drop explicitly so a
    # subsequent upgrade does not fail with "type already exists".
    bind = op.get_bind()
    for enum_name in ('animaltype', 'gender', 'animalstatus'):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
